### ISSUE TITLE
#[derive(SerdeValue)] could not find `erased_serde` in `{{root}}`

### ISSUE THREAD

**Issue by spearman** [slog-rs/derive#7]
When I try to use #[derive(SerdeValue)] with the following Cargo.toml dependencies, I get this error:

```
[dependencies]
sloggers = "0.3.*"
slog_derive = "0.2.*"
slog = { version = "2.*", features = ["nested-values"] }
serde = { version = "1.*", features = ["derive"] }
```

And here is the program:

```
use serde::{Deserialize, Serialize};
use slog;
use sloggers;
use slog_derive::{KV, SerdeValue};

#[derive(Debug, Deserialize, Serialize, KV)]
struct Myrecord {
 pub a : String,
 pub b : B
}

#[derive(Clone, Debug, Deserialize, Serialize, SerdeValue)]
pub struct B {
  pub b : u8
}

fn main() {
  let log_root = {
    let mut builder = sloggers::terminal::TerminalLoggerBuilder::new();
    builder.level(sloggers::types::Severity::Debug);
    sloggers::Build::build (&builder).unwrap()
  };
  let myrec = Myrecord {
    a: "hello".to_string(),
    b: B { b: 5 }
  };
  slog::info!(log_root, ""; myrec);
}

```

**Comment by Michael-F-Bryan** [comment]
> I get this error

Can you paste the error message you are seeing?

**Comment by spearman** [comment]
Ah, sorry "this error" referred to the the title of this issue, full error:
```
% cargo run
   Compiling tryslog v0.1.0 (/home/spearman/rs/try/tryslog2)
error[E0433]: failed to resolve: could not find `erased_serde` in `{{root}}`
  --> src/main.rs:12:48
   |
12 | #[derive(Clone, Debug, Deserialize, Serialize, SerdeValue)]
   |                                                ^^^^^^^^^^ could not find `erased_serde` in `{{root}}`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0433`.
error: could not compile `tryslog`.

To learn more, run the command again with --verbose.
```

**Comment by Michael-F-Bryan** [comment]
It looks like you need to add `erased_serde` as a dependency in your `Cargo.toml`. 

The `SerdeValue` trait returns an `&dyn erased_serde::Serialize`, so when we [generate the `SerdeValue` impl](https://github.com/slog-rs/derive/blob/36b1e9bb8ded5c7ec97bd3fb33048573b58696d5/src/derive_serde_value.rs#L11-L18) it tries to reference a type that `rustc` can't find.

The `slog_derive` crate can't really work around this because procedural macro crates aren't allowed to export anything other than procedural macros. It's why you can't just add `serde_derive` to a crate and write `#[derive(Serialize, Deserialize)]`, you also need to add `serde` as a dependency so the generated code has access to the traits and types it's referencing.
